name = "ProblemReductions"
uuid = "899c297d-f7d2-4ebf-8815-a35996def416"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BitBasis = "50ba71b6-fa0f-514d-ae9a-0916efc90dcf"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
UnitDiskMapping = "1b61a8d9-79ed-4491-8266-ef37f39e1727"

[compat]
BitBasis = "0.9"
Graphs = "1"
UnitDiskMapping = "0.3, 0.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
